all: FindDevices NewAddress EncTurn EncTurnLeftRight FindDevices KeyChanged KeyHold KeyPressed KeyPushed KeyReleased KeyTimePressed KeyTrigger NewAddress PinModeDAC PinModeFrequency PinModeKey PinModeOff PinModePWM PinModePWMlog PinModeServo PinModeTrigger PositionGet PositionReset PositionSettings

FindDevices             :FindDevices.cpp ../iarduino_I2C_Encoder.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Encoder.cpp
EncTurn                 :EncTurn.cpp ../iarduino_I2C_Encoder.cpp
EncTurnLeftRight        :EncTurnLeftRight.cpp ../iarduino_I2C_Encoder.cpp
FindDevices             :FindDevices.cpp ../iarduino_I2C_Encoder.cpp
KeyChanged              :KeyChanged.cpp ../iarduino_I2C_Encoder.cpp
KeyHold                 :KeyHold.cpp ../iarduino_I2C_Encoder.cpp
KeyPressed              :KeyPressed.cpp ../iarduino_I2C_Encoder.cpp
KeyPushed               :KeyPushed.cpp ../iarduino_I2C_Encoder.cpp
KeyReleased             :KeyReleased.cpp ../iarduino_I2C_Encoder.cpp
KeyTimePressed          :KeyTimePressed.cpp ../iarduino_I2C_Encoder.cpp
KeyTrigger              :KeyTrigger.cpp ../iarduino_I2C_Encoder.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Encoder.cpp
PinModeDAC              :PinModeDAC.cpp ../iarduino_I2C_Encoder.cpp
PinModeFrequency        :PinModeFrequency.cpp ../iarduino_I2C_Encoder.cpp
PinModeKey              :PinModeKey.cpp ../iarduino_I2C_Encoder.cpp
PinModeOff              :PinModeOff.cpp ../iarduino_I2C_Encoder.cpp
PinModePWM              :PinModePWM.cpp ../iarduino_I2C_Encoder.cpp
PinModePWMlog           :PinModePWMlog.cpp ../iarduino_I2C_Encoder.cpp
PinModeServo            :PinModeServo.cpp ../iarduino_I2C_Encoder.cpp
PinModeTrigger          :PinModeTrigger.cpp ../iarduino_I2C_Encoder.cpp
PositionGet             :PositionGet.cpp ../iarduino_I2C_Encoder.cpp
PositionReset           :PositionReset.cpp ../iarduino_I2C_Encoder.cpp
PositionSettings        :PositionSettings.cpp ../iarduino_I2C_Encoder.cpp

clean:
	rm -f FindDevices NewAddress EncTurn EncTurnLeftRight FindDevices KeyChanged KeyHold KeyPressed KeyPushed KeyReleased KeyTimePressed KeyTrigger NewAddress PinModeDAC PinModeFrequency PinModeKey PinModeOff PinModePWM PinModePWMlog PinModeServo PinModeTrigger PositionGet PositionReset PositionSettings
