all: FindDevices NewAddress

FindDevices             :FindDevices.cpp ../iarduino_I2C_Encoder.cpp
NewAddress              :NewAddress.cpp ../iarduino_I2C_Encoder.cpp

clean:
	rm -f FindDevices NewAddress
